#%RAML 0.8
---
title:  简账
#version: v0.1
baseUri: http://rankun.org:8899
mediaType: application/json

documentation:
  - title: Contribution
    content: !include doc/contribution.md

traits:
  # 写操作成功
  - respWithoutPayload:
      responses:
        200:
          body:
            application/json:
              example: |
                {
                  "code": 1000,
                  "msg": "正常返回",
                  "palyoad": null
                }
  # 返回失败信息
  - respWithError:
      responses:
        200:
          body:
            application/json:
              schema: SimpleResponse
              example: |
                {
                  "code": <<errorCode>>,
                  "msg": "<<msg>>",
                  "palyoad": <<payload>>
                }
  # 接口响应中包含 data 字段
  - respWithPayload:
      responses:
        200:
          body:
            application/json:
              example: |
                {
                  "code": 1000,
                  "msg": "正常返回",
                  "payload": <<payload>>
                }
  # 接口响应的描述
  - responseDesc:
      responses:
        200:
          description: <<desc>>

/entry:
  displayName: 登录注册
  /login:
    post:
      description: 登录
      queryParameters:
        phone:
          description: 手机号码，18166662727
        password:
          description: 密码
  /register:
    post:
      description: 注册
      queryParameters:
        phone:
          description: 手机号码，18166662727
        password:
          description: 密码
      is:
        - responseDesc:
            desc: 删除成功
        - respWithoutPayload
  /sendVerifyCode:
    post:
      description: 发送验证码，SMS
      queryParameters:
        phone:
          description: 手机号码，18166662727
      is:
        - responseDesc:
            desc: 删除成功
        - respWithoutPayload
  /resetPassword:
    post:
      description: 重置密码
      queryParameters:
        phone:
          description: 手机号码，18166662727
          required: true
          type: string
        newPassword:
          description: 新密码
          required: true
          type: string
      is:
        - responseDesc:
            desc: 重置密码成功
        - respWithoutPayload
/books:
  displayName: 账本操作
  /:
    post:
      description: 添加账本
      queryParameters:
        name:
          description: 账本名字
          required: true
        nativeCurrency:
          description: 账本币种，CNY, USD 等
        financialYear:
          description: 财务年度，年份数字，2015、2016等
          type: number
          default: 当前年份
          required: false
        comment:
          description: 备注，支持
      is:
        - responseDesc:
            desc: 添加成功
        - respWithoutPayload
  /{id}:
    get:
      description: 获取该账本
      is:
        - responseDesc:
            desc:  返回账本信息
        - respWithPayload:
            payload: !include samples/book.sample
    put:
      description: 修改账本信息
      queryParameters:
        name:
          description: 账本名字
        comment:
          description: 备注，支持
      is:
        - responseDesc:
            desc: 更新成功
        - respWithoutPayload
    delete:
      description: 删除账本
      is:
        - responseDesc:
            desc: 删除成功
        - respWithoutPayload
/books/{id}/bookkeeping:
  displayName: 记账
  /income:
    post:
      description: 记收入
      queryParameters:
        inoutTypeId:
          type: number
          description: 收支类别 ID，是属于哪一个类别的收支？参考 收支类别的 ID
          required: true
        incomeAccountId:
          description: 收入账户
          type: number
          required: true
        amount:
          description: 收入的金额
          type: number
        tradeTime:
          description: 交易日期
          type: number
          required: true
        businessUnitId:
          description: 往来单位 ID
          type: number
        projectId:
          description: 相关项目 ID
          type: number
        staffId: 
          description: 经办人、员工 ID
          type: number
        departmentId:
          description: 部门 ID
          type: number
        comment:
          description: 备注内容
        attachmentUrl:
          description: 附件URL, 相对地址，文件的 Key
      is:
        - responseDesc:
            desc: 记录成功
        - respWithoutPayload
  /expense:
    post:
      description: 记支出
      queryParameters:
        inoutTypeId:
          type: number
          description: 收支类别 ID，是属于哪一个类别的收支？参考 收支类别的 ID
          required: true
        expenseAccountId:
          description: 支出账户
          type: number
          required: true
        amount:
          description: 支出的金额
          type: number
        tradeTime:
          description: 交易日期
          type: number
          required: true
        businessUnitId:
          description: 往来单位 ID
          type: number
        projectId:
          description: 相关项目 ID
          type: number
        staffId: 
          description: 经办人、员工 ID
          type: number
        departmentId:
          description: 部门 ID
          type: number
        comment:
          description: 备注内容
        attachmentUrl:
          description: 附件URL, 相对地址，文件的 Key
      is:
        - responseDesc:
            desc: 记录成功
        - respWithoutPayload
  /transfer:
    post:
      description: 记转账，资金调拨
      queryParameters:
        inoutTypeId:
          type: number
          description: 收支类别 ID，是属于哪一个类别的收支？参考 收支类别的 ID
          required: true
        incomeAccountId:
          description: 转入账户
          type: number
          required: true
        expenseAccountId:
          description: 转出账户
          type: number
          required: true
        amount:
          description: 转账金额
          type: number
        tradeTime:
          description: 交易日期
          type: number
          required: true
        businessUnitId:
          description: 往来单位 ID
          type: number
        projectId:
          description: 相关项目 ID
          type: number
        staffId: 
          description: 经办人、员工 ID
          type: number
        departmentId:
          description: 部门 ID
          type: number
        comment:
          description: 评论内容
        attachmentUrl:
          description: 附件URL, 相对地址，文件的 Key
      is:
        - responseDesc:
            desc: 记录成功
        - respWithoutPayload
  /begin:
    post:
      description: 记初始
      queryParameters:
        incomeAccountId:
          description: 要初始化的账户
          type: number
          required: true
        amount:
          description: 初始化的金额
          type: number
        tradeTime:
          description: 交易日期
          type: number
          required: true
        businessUnitId:
          description: 往来单位 ID
          type: number
        projectId:
          description: 相关项目 ID
          type: number
        staffId: 
          description: 经办人、员工 ID
          type: number
        departmentId:
          description: 部门 ID
          type: number
        comment:
          description: 评论内容
        attachmentUrl:
          description: 附件URL, 相对地址，文件的 Key
      is:
        - responseDesc:
            desc: 记录成功
        - respWithoutPayload
  /headging:
    post:
      description: 记对冲
      queryParameters:
        amount:
          description: 支出的金额
          type: number
        tradeTime:
          description: 交易日期
          type: number
          required: true
        businessUnitId:
          description: 往来单位 ID
          type: number
        payableId:
          description: 应付条目 ID
          type: number
        receivableid:
          description: 应收条目 ID
          type: number
        projectId:
          description: 相关项目 ID
          type: number
        staffId: 
          description: 经办人、员工 ID
          type: number
        departmentId:
          description: 部门 ID
          type: number
        comment:
          description: 备注内容
        attachmentUrl:
          description: 附件URL, 相对地址，文件的 Key
      is:
        - responseDesc:
            desc: 记录成功
        - respWithoutPayload
  /refund:
    post:
      description: 记退款
      queryParameters:
        inoutTypeId:
          type: number
          description: 收支类别 ID，是属于哪一个类别的收支？参考 收支类别的 ID
          required: true
        amount:
          description: 交易金额
          type: number
        tradeTime:
          description: 交易日期
          type: number
          required: true
        businessUnitId:
          description: 往来单位 ID
          type: number
        projectId:
          description: 相关项目 ID
          type: number
        staffId: 
          description: 经办人、员工 ID
          type: number
        departmentId:
          description: 部门 ID
          type: number
        comment:
          description: 备注内容
        attachmentUrl:
          description: 附件URL, 相对地址，文件的 Key
      is:
        - responseDesc:
            desc: 记录成功
        - respWithoutPayload
  /reconciliation:
    post:
      description: x - 对账
      queryParameters:
        inoutTypeId:
          type: number
          description: 收支类别 ID，是属于哪一个类别的收支？参考 收支类别的 ID
          required: true
        amount:
          description: 交易金额
          type: number
        tradeTime:
          description: 交易日期
          type: number
          required: true
        staffId: 
          description: 经办人、员工 ID
          type: number
        departmentId:
          description: 部门 ID
          type: number
        comment:
          description: 备注内容
        attachmentUrl:
          description: 附件URL, 相对地址，文件的 Key
      is:
        - responseDesc:
            desc: 记录成功
        - respWithoutPayload
/books/{id}/report:
  displayName: 报表
  /income:
    get:
      description: 获取收入报表，参数为筛选条件
      queryParameters:
        start:
          description: 统计开始日期
          type: number
        until:
          description: 统计截至日期
          type: number
      is:
        - responseDesc:
            desc: 返回收入报表
        - respWithPayload:
            payload: !include samples/reportIncome.sample
  /expense:
    get:
      description: 获取支出报表，参数为筛选条件
      queryParameters:
        start:
          description: 统计开始日期
          type: number
        until:
          description: 统计截至日期
          type: number
      is:
        - responseDesc:
            desc: 返回支出报表
        - respWithPayload:
            payload: !include samples/reportExpense.sample
  /profit:
    get:
      description: 获取利润报表，参数为筛选条件
      queryParameters:
        start:
          description: 统计开始日期
          type: number
        until:
          description: 统计截至日期
          type: number
      is:
        - responseDesc:
            desc: 返回利润报表
        - respWithPayload:
            payload: !include samples/reportProfit.sample
  /cash:
    get:
      description: 获取现金流量报表，参数为筛选条件
      queryParameters:
        start:
          description: 统计开始日期
          type: number
        until:
          description: 统计截至日期
          type: number
      is:
        - responseDesc:
            desc: 返回现金流量报表
        - respWithPayload:
            payload: !include samples/reportCash.sample
  /debit:
    get:
      description: 资产负债报表，参数为筛选条件
      queryParameters:
        start:
          description: 统计开始日期
          type: number
        until:
          description: 统计截至日期
          type: number
      is:
        - responseDesc:
            desc: 返回负债报表
        - respWithPayload:
            payload: !include samples/reportCash.sample
  /accountBalance:
    get:
      description: 获取账户余额报表，参数为筛选条件
      queryParameters:
        start:
          description: 统计开始日期
          type: number
        until:
          description: 统计截至日期
          type: number
      is:
        - responseDesc:
            desc: 返回账户余额报表
        - respWithPayload:
            payload: !include samples/reportAccountBalance.sample
/books/{id}/inventory:
  displayName: 库存
  /items:
    /:
      get:
        description: 获取货品列表
      post:
        description: 新增货品
    /{itemId}:
      get:
        description: 获取货品信息
      put:
        description: 货物调拨
  /storage:
    /:
      get:
        description: 获取库房列表
      post:
        description: 添加库房
    /{storageId}:
      get:
        description: 获取库房信息
      delete:
        description: 删除库房
      put:
        description: 更新库房信息
  /deliveryManifest:
    get:
      description: 出货单，参数为筛选条件
      queryParameters:
        start:
          description: 统计开始日期
          type: number
        until:
          description: 统计截至日期
          type: number
        inventoryId:
          description: 指定仓库 ID
          type: number
        clientId:
          description: 客户 ID
          type: number
      is:
        - responseDesc:
            desc: 返回出货单
        - respWithPayload:
            payload: !include samples/inventoryDeliveryManifest.sample
  /itemsManifest:
    get:
      description: 明细单，参数为筛选条件
      queryParameters:
        start:
          description: 指定统计开始日期
          type: number
        until:
          description: 指定统计截至日期
          type: number
        inventoryId:
          description: 指定仓库 ID
          type: number
        clientId:
          description: 客户 ID
          type: number
      is:
        - responseDesc:
            desc: 返回详情单
        - respWithPayload:
            payload: !include samples/inventoryItemsManifest.sample
  /assemble:
    post:
      description: 组装货物，拆分货物
      queryParameters:
        type:
          description: 1：组装货物、2：拆分货物
          type: number
        fromItems:
          description: 输入货物列表, JSON 数组，在 JSON 中传的时候不用封装成字符串
          type: string
          example: !include samples/itemList.sample
        toItems:
          description: 输出货物列表, JSON 数组，在 JSON 中传的时候不用封装成字符串
          type: string
          example: !include samples/itemList.sample
        comment:
          description: 备注
        activityTime:
          description: 活动发生的时间
        storageId:
          description: 库房 ID
  /inout:
    post:
      description: 进货出货
      queryParameters:
        type:
          description: 1：销售出货、2：采购进货、3：销售退货、4：采购退货、5：借货销售
          type: number
        businessUnitId:
          description: 往来单位
        activityTime:
          description: 活动发生的时间
        incomeAccountId:
          description: 收款账户
        expenseAccountId:
          description: 付款账户
        storageId:
          description: 仓库 ID
        projectId:
          description: 项目 ID
        staffId:
          description: 经办人、员工 ID
        departmentId:
          description: 部门 ID
        totalAmount:
          description: 总价
        comment:
          description: 备注
        items:
          description: 货物列表, JSON 数组
          type: string
          example: !include samples/itemList.sample
      is:
        - responseDesc:
            desc: 操作成功
        - respWithoutPayload
  /relocate:
    post:
      description: 货物调拨
      queryParameters:
        activityTime:
          description: 活动发生的时间
        fromStorageId:
          description: 调出库房
        toStorageId:
          description: 调入库房
        staffId:
          description: 经办人、员工 ID
        departmentId:
          description: 部门 ID
        comment:
          description: 备注
        items:
          description: 货物列表，JSON 数组
          type: string
          example: !include samples/itemList.sample
      is:
        - responseDesc:
            desc: 操作成功
        - respWithoutPayload
  /adjustPrice:
    put:
      description: 货物调价
      queryParameters:
        activityTime:
          description: 活动发生的时间
        storageId:
          description: 仓库 ID
        staffId:
          description: 经办人、员工 ID
        departmentId:
          description: 部门 ID
        totalAmount:
          description: 总价
        comment:
          description: 备注
        items:
          description: 调价的货物列表, JSON 数组, itemPrice 即该物品的新价格
          type: string
          example: !include samples/itemListAdjustPrice.sample
      is:
        - responseDesc:
            desc: 操作成功
        - respWithoutPayload
  /stockTaking:
    get:
      description: 盘点库存
      queryParameters:
        activityTime:
          description: 活动发生的时间
        storageId:
          description: 仓库 ID
        staffId:
          description: 经办人、员工 ID
        departmentId:
          description: 部门 ID
        totalAmount:
          description: 总价，合计
        comment:
          description: 备注
        items:
          description: 库存盘点的货物列表, JSON 数组, itemCount 即该物品的现有数量
          type: string
          example: !include samples/itemListStockTaking.sample
      is:
        - responseDesc:
            desc: 操作成功
        - respWithoutPayload
  /costTransfer:
    post:
      description: 成本结转
      queryParameters:
        activityTime:
          description: 活动发生的时间
        storageId:
          description: 仓库 ID
        staffId:
          description: 经办人、员工 ID
        departmentId:
          description: 部门 ID
        totalAmount:
          description: 总价，合计
        comment:
          description: 备注
        items:
          description: 成本结转的货物列表, JSON 数组, itemCount 即该物品的现有数量，itemPrice 即成本价，totalAmount 即核算成本，将会增加到成本支出里面
          type: string
          example: !include samples/itemListCostTransfer.sample
      is:
        - responseDesc:
            desc: 操作成功
        - respWithoutPayload
    get:
      description: 获取成本结转历史记录，参数为筛选条件
      queryParameters:
        start:
          description: 记录获取开始日期
          type: number
        until:
          description: 记录获取截至日期
          type: number
        storageId:
          description: 指定仓库 ID
          type: number
        clientId:
          description: 客户 ID
          type: number
        orderNo:
          description: 订单号码

      is:
        - responseDesc:
            desc: 返回成本转结历史记录
        - respWithPayload:
            payload: !include samples/costTransferLog.sample
/books/{id}/settings:
  displayName: 其它设置相关的数据
  /people:
    /:
      get:
        description: 获取员工、客户、供应商等列表
        queryParameters:
          type:
            description: 人员类别，1：客户、2：员工、3：供应商
            type: number
        is:
          - responseDesc:
              desc: 返回人员列表
          - respWithPayload:
              payload: !include samples/generalPeople.sample
      post:
        description: 添加员工、酷虎、供应商等记录
        queryParameters:
          type:
            description: 人员类别，1：客户、2：员工、3：供应商
            type: number
          name: 
            description: 姓名，张三
          phone: 
            description: 手机号码，18166662727
          email: 
            description: 邮箱，san@gmail.com
          qq: 
            description: QQ 号，56789765
          address: 
            description: 地址，四川，广州，上海
          comment: 
            description: 备注
        is:
          - responseDesc:
              desc: 添加成功
          - respWithoutPayload
    /{uid}:
      get:
        description: 获取员工、酷虎、供应商等记录
        is:
          - responseDesc:
              desc: 返回该对象
          - respWithPayload:
              payload: !include samples/generalPeoplePerson.sample
      put:
        description: 修改员工、酷虎、供应商等记录
        queryParameters:
          type:
            description: 人员类别，1：客户、2：员工、3：供应商
            type: number
          name: 
            description: 姓名，张三
          phone: 
            description: 手机号码，18166662727
          email: 
            description: 邮箱，san@gmail.com
          qq: 
            description: QQ 号，56789765
          address: 
            description: 地址，四川，广州，上海
          comment: 
            description: 备注
        is:
          - responseDesc:
              desc: 修改成功
          - respWithoutPayload
      delete:
        description: 删除用户权限
        is:
          - responseDesc:
              desc: 删除成功
          - respWithoutPayload
  /departments:
    /:
      get:
        description: 获取部门列表
        is:
          - responseDesc:
              desc: 返回部门列表
          - respWithPayload:
              payload: !include samples/generalDepartmentList.sample
      post:
        description: 增加部门
        queryParameters:
          name:
            description: 部门名称
          comment:
            description: 部门备注
        is:
          - responseDesc: 
              desc: 增加成功
          - respWithoutPayload
    /{departmentId}:
      get:
        description: 获取部门详情
        is:
          - responseDesc:
              desc: 返回部门信息
          - respWithPayload:
              payload: !include samples/generalDepartment.sample
      put:
        description: 更新部门详情
        queryParameters:
          name:
            description: 部门名称
          comment:
            description: 部门描述
        is:
          - responseDesc:
              desc: 更新成功
          - respWithoutPayload
      delete:
        description: 删除用户权限
        is:
          - responseDesc:
              desc: 删除成功
          - respWithoutPayload
  /projects:
    /:
      get:
        description: 获取 项目列表
        is:
          - responseDesc:
              desc: 返回项目列表
          - respWithPayload:
              payload: !include samples/generalProjectList.sample
      post:
        description: 增加项目
        queryParameters:
          name:
            description: 项目名称
          comment:
            description: 项目备注
        is:
          - responseDesc: 
              desc: 增加成功
          - respWithoutPayload
    /{projectId}:
      get:
        description: 获取项目详情
        is:
          - responseDesc:
              desc: 返回项目信息
          - respWithPayload:
              payload: !include samples/generalProject.sample
      put:
        description: 更新项目详情
        queryParameters:
          name:
            description: 项目名称
          comment:
            description: 项目描述
        is:
          - responseDesc:
              desc: 更新成功
          - respWithoutPayload
      delete:
        description: 删除用户权限
        is:
          - responseDesc:
              desc: 删除成功
          - respWithoutPayload
  /inoutTypes:
    /:
      get:
        description: 获取收入支出分类列表
        queryParameters:
          type:
            description: 收入支出分类，1：收入，2：支出
            type: number
        is:
          - responseDesc:
              desc: 返回收入支出分类列表
          - respWithPayload:
              payload: !include samples/generalInoutTypes.sample
      post:
        description: 添加收入支出分类等记录
        queryParameters:
          type:
            description: 收入支出分类，1：收入，2：支出
            type: number
          name: 
            description: 收入支出的名字，进货支出、设备损坏等
          comment: 
            description: 备注
        is:
          - responseDesc:
              desc: 添加成功
          - respWithoutPayload
    /{typeId}:
      get:
        description: 获取收入支出分类等记录
        is:
          - responseDesc:
              desc: 返回该对象
          - respWithPayload:
              payload: !include samples/generalInoutType.sample
      put:
        description: 修改收入支出分类等记录
        queryParameters:
          name: 
            description: 收入支出的名字，进货支出、设备损坏等
          comment: 
            description: 备注
        is:
          - responseDesc:
              desc: 修改成功
          - respWithoutPayload
      delete:
        description: 删除用户权限
        is:
          - responseDesc:
              desc: 删除成功
          - respWithoutPayload
  /currencyRate:
    /:
      get:
        description: 获取我的汇率列表，分页接口
        is:
          - responseDesc:
              desc: 返回我的汇率列表
          - respWithPayload:
              payload: !include samples/generalRateList.sample
      post:
        description: 设置最新的汇率
        queryParameters:
          thisCurrency:
            description: 本币
          oppositeCurrency:
            description: 外币
          startTime:
            description: 生效起始时间
        is:
          - responseDesc:
              desc: 添加成功
          - respWithoutPayload
  /accessableUsers:
    /:
      get:
        description: 获取该账本的所有可以访问的人
        is:
          - responseDesc:
              desc: 返回可以访问该账本的人的列表
          - respWithPayload:
              payload: !include samples/generalAccessableUserList.sample
      post:
        description: 设置最新的汇率
        queryParameters:
          name: 
            description: 张四
          phone: 
            description: 18166662728
          job: 
            description: 职务类别，1：财务，2：库管
            type: number
        is:
          - responseDesc:
              desc: 添加成功
          - respWithoutPayload
    /{uid}:
      put:
        description: 更新用户权限
        queryParameters:
          name: 
            description: 张四
          phone: 
            description: 18166662728
          job: 
            description: 职务类别，1：财务，2：库管
            type: number
        is:
          - responseDesc:
              desc: 更新成功
          - respWithoutPayload
      delete:
        description: 删除用户权限
        is:
          - responseDesc:
              desc: 删除成功
          - respWithoutPayload
  /actionHistory:
    get:
      description: 获取操作历史
      queryParameters:
        start:
          description: 统计开始日期
          type: number
        until:
          description: 统计截至日期
          type: number
        uid:
          description: 指定用户的操作历史
          type: number
        action:
          description: 操作类型，
          type: number
      is:
        - responseDesc:
            desc: 返回我的汇率列表
        - respWithPayload:
            payload: !include samples/generalActionHistory.sample
  /recycleBin:
    /:
      get:
        description: 返回回收站的条目列表
        queryParameters:
          actionUid:
            description: 操作用户 ID
            type: number
          type:
            description: 操作类型
            type: number
        is:
          - responseDesc:
              desc: 返回回收站的条目列表
          - respWithPayload:
              payload: !include samples/generalRecycleBinItems.sample
    /{binId}:
      put:
        description: 更新回收站条目
        queryParameters:
          action:
            description: 操作，1：恢复，2：彻底删除
            type: number
        is:
          - responseDesc:
              desc: 操作成功
          - respWithoutPayload
